### PR TITLE
Fix min delay error

### LINKED ISSUE #411: ``min_delay`` error with NEST 2.10
Config: Python 3.5, NEST 2.10.0 and PyNN 0.8.0

Trying to run the example file from [the doc](http://neuralensemble.org/docs/PyNN/examples/Izhikevich.html) with NEST I ran into the following problem:

running ``python ex.py nest`` returned

        sim.setup(timestep=0.01, min_delay=1.0)
      File "/usr/lib/python3.5/site-packages/pyNN/nest/__init__.py", line 128, in setup
        simulator.state.set_delays(min_delay, max_delay)
      File "/usr/lib/python3.5/site-packages/pyNN/nest/simulator.py", line 94, in set_delays
        'max_delay': max_delay})
      File "/home/me/.nest-2.10.0-install/lib/python3.5/site-packages/nest/lib/hl_api_helper.py", line 138, in stack_checker_func
        return f(*args, **kwargs)
      File "/home/me/.nest-2.10.0-install/lib/python3.5/site-packages/nest/lib/hl_api_models.py", line 91, in SetDefaults
        sr('/{0} exch SetDefaults'.format(model))
      File "/home/me/.nest-2.10.0-install/lib/python3.5/site-packages/nest/__init__.py", line 79, in catching_sli_run
        raise _kernel.NESTError("{0} in {1}{2}".format(errorname, commandname, message))
    pynestkernel.NESTError: BadProperty in SetDefaults_l_D: Setting status of prototype 'gap_junction': gap_junction connection has no delay

The error goes away without ``sim.setup(timestep=0.01, min_delay=1.0)``, using ``sim.setup(timestep=0.01)`` only.

### PR DESCRIPTION
**Pull request by mschmidt87**
This PR supersedes #413 .

In NEST, min_delay is no longer set in the defaults of each synapse but min_delay is set globally in the NEST kernel.
This fixes #411 .

In addition, the install_nest.sh script for Travis was changed to download and build the current master from [https://github.com/nest/nest-simulator](https://github.com/nest/nest-simulator). To achieve this, I removed the possibility to fall back on cached code so that Travis always checks with the current master branch of NEST.

### CODE REVIEW

**Comment by apdavison** [comment]
I guess you saw the error message from Travis: "CMake 2.8.12 or higher is required.  You are running version 2.8.7"

File: ci/install_nest.sh [hunk 1]
```diff
@@ -2,33 +2,20 @@
 
 set -e  # stop execution in case of errors
 
-if [[ "$TRAVIS_PYTHON_VERSION" == "2.7_with_system_site_packages" ]]; then
```
Comment (apdavison) [inline ci/install_nest.sh]: Please keep this if statement; we only run the full test suite for this Python version, for the other versions NEST is not required, so we can save time by not installing it.

**Comment by mschmidt87** [comment]
Yes, I saw the error mesage about cmake but don't know what to do about it. My last commit was my attempt to add cmake to the packages that Travis installs so that it gets the newest version of cmake. My change repeats what is done in NEST, but it seems that it doesn't work. Do you have an idea how to solve it?

**Comment by apdavison** [comment]
It seems that NEST is using the [Trusty beta build environment](https://docs.travis-ci.com/user/trusty-ci-environment/), which evidently has a newer version of cmake.

**Comment by mschmidt87** [comment]
Okay, so can the Travis account of PyNN be switched to Trusty beta? I guess, you would have to do that, right?

**Comment by apdavison** [comment]
@mschmidt87 I've made the switch to Trusty beta, but I can't get the NEST master branch to build in Travis - see https://travis-ci.org/apdavison/PyNN/jobs/169648561

Can you figure out what is going on?

**Comment by apdavison** [comment]
ok, NEST master branch is now building in Travis with both Python 2.7 and 3.5. The problem was with shared libraries not being available in the virtualenv. There is still a unrelated error, but `min_delay` now works properly.
